//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTLWEB2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartView
    {
        public Nullable<long> totalCart { get; set; }
        public int MaChiTietGioHang { get; set; }
        public int MaGioHang { get; set; }
        public string MaSize { get; set; }
        public string MaSP { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string Anh { get; set; }
        public Nullable<int> Gia { get; set; }
        public string TenSP { get; set; }
    }
}
