//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTLWEB2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tChiTietHoaDon
    {
        public int MaChiTietHoaDon { get; set; }
        public int MaHD { get; set; }
        public string MaSP { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        public virtual tHoaDon tHoaDon { get; set; }
        public virtual tSanPham tSanPham { get; set; }
    }
}
