//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTLWEB2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tTaiKhoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tTaiKhoan()
        {
            this.tHoaDons = new HashSet<tHoaDon>();
        }
    
        [Required(ErrorMessage = "Vui lòng nhập tên tài khoản ")]
        public string TenTK { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập mật khẩu ")]
        public string Password { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập tên khách hàng ")]
        public string TenKH { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập email ")]
        public string Email { get; set; }
        public Nullable<bool> XacMinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tHoaDon> tHoaDons { get; set; }
    }
}
